{
 "title": "Pizza Dashboard",
 "description": "Dashboard to show all jwt-pizza-service stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_request_total", "legendFormat": "__auto" },
    { "expr": "http_request_get_total", "legendFormat": "__auto" },
    { "expr": "http_request_post_total", "legendFormat": "__auto" },
    { "expr": "http_request_put_total", "legendFormat": "__auto" },
    { "expr": "http_request_delete_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(auth_success_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_failure_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" },
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "pizzas_sold_total", "legendFormat": "__auto" },
    { "expr": "creation_failures_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "latency_service_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "latency_createPizza_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}